# This is an example of what an '_config.yml' file should look like
# when using jekyll-shell-theme. You should use this as a guide or
# just copy+paste it and modify some of the content to begin with.

title: Yona Lapeyre's website
tagline: my personal webpage
email: yona.lapeyre@ens-lyon.fr
description: >- # this means to ignore newlines until "baseurl:"
  You'll find updates of my adventures in the reign of astrophysics and  high performance computing.
baseurl: "/y-lapeyre" # the subpath of your site
url: "https://y-lapeyre.github.io" # the base hostname & protocol for your site
github_username:  y-lapeyre

# Required plugins for the theme to work properly
plugins:
  - jekyll-remote-theme
  - jemoji

# Including jekyll-shell-theme using the jekyll-remote-theme plugin
remote_theme: tareqdandachi/jekyll-shell-theme

#sass:
#  style: compressed

highlighter: rouge #selecting the highlighter, default is rouge

header_pages:
  - index.md
  - about.md
  - a-third-page.md
 
# controls how big the shell and font looks
font-size: small # options: [small] or [large]

lang: en
timezone: Europe/Paris
social:
  email: yona.lapeyre@ens-lyon.fr
  links:
    - https://github.com/y-lapeyre

avatar:
  src: assets/splash_0118.png
  alt: Yona Lapeyre

theme_settings:
  css: assets/css/main.scss

 