title: "Yona Lapeyre"
tagline: "My personal website :)"
description: "I'll try to update often"
github_username: y-lapeyre
baseurl: "/y-lapeyre"
url: "https://y-lapeyre.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
